using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pos.Function
{
    internal class ListPermission
    {
        public static List<Pos.Models.Permission> GetPredefinedPermissions()
        {
            return new List<Pos.Models.Permission>
            {
                new Pos.Models.Permission { Name = "Add Customer", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Customer", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Customer", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Customers", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add User", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit User", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete User", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Users", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Case", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Case", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Case", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Case Type", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Case Type", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Case Type", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Case Types", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Judicial Authority", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Judicial Authority", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Judicial Authority", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Judicial Authorities", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Section", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Section", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Section", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Sections", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Location Session", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Location Session", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Location Session", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Location Sessions", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Office Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Statistics", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Permission", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Permission", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Permission", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Permissions", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Role", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Role", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Role", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Roles", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Settings", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Reminder Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Today Summary", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Alert Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Lock Screen", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Location", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Location", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Location", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Locations", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Basic Laws", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Templates", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Files", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Printer", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Printer", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Printer", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Printers", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Expense", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Expense", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Expense", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Expenses", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Expense Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Expense Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Expense Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Expense Categories", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Dashboard", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Currency", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Currency", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Currency", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Currencies", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Business Location", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Business Location", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Business Location", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Business Locations", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Service", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Service", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Service", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Services", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Fee Payment", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "View Customer Details", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Send emails to all customers", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Customer badge printing", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Template Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Template Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete All Templates", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Template", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Upload Template", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Select a template", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Case Quick View", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Payments Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Latest Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Closest Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Favorite Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Winning Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Blacklisted Cases", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Cases Of Withdrawn Files", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Basic Law Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Basic Law Category", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Tasks", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Task", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Task", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Task", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "List Taxes", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Add Tax", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Edit Tax", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Delete Tax", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
                new Pos.Models.Permission { Name = "Audit Trail", CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now },
            }; 
        }
    }
}
