using DevExpress.Office.Utils;
using DevExpress.XtraRichEdit.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pos.Function
{
    internal class PhoneCode
    {
        public static List<CountryInfo> GetCountryPhoneCodes()
        {
             return new List<CountryInfo>
                {
                    new CountryInfo("Afghanistan", "+93"),
                    new CountryInfo("Albania", "+355"),
                    new CountryInfo("Algeria", "+213"),
                    new CountryInfo("Andorra", "+376"),
                    new CountryInfo("Angola", "+244"),
                    new CountryInfo("Antigua and Barbuda", "+1-268"),
                    new CountryInfo("Argentina", "+54"),
                    new CountryInfo("Armenia", "+374"),
                    new CountryInfo("Australia", "+61"),
                    new CountryInfo("Austria", "+43"),
                    new CountryInfo("Azerbaijan", "+994"),
                    new CountryInfo("Bahamas", "+1-242"),
                    new CountryInfo("Bahrain", "+973"),
                    new CountryInfo("Bangladesh", "+880"),
                    new CountryInfo("Barbados", "+1-246"),
                    new CountryInfo("Belarus", "+375"),
                    new CountryInfo("Belgium", "+32"),
                    new CountryInfo("Belize", "+501"),
                    new CountryInfo("Benin", "+229"),
                    new CountryInfo("Bhutan", "+975"),
                    new CountryInfo("Bolivia", "+591"),
                    new CountryInfo("Bosnia and Herzegovina", "+387"),
                    new CountryInfo("Botswana", "+267"),
                    new CountryInfo("Brazil", "+55"),
                    new CountryInfo("Brunei", "+673"),
                    new CountryInfo("Bulgaria", "+359"),
                    new CountryInfo("Burkina Faso", "+226"),
                    new CountryInfo("Burundi", "+257"),
                    new CountryInfo("Cabo Verde", "+238"),
                    new CountryInfo("Cambodia", "+855"),
                    new CountryInfo("Cameroon", "+237"),
                    new CountryInfo("Canada", "+1"),
                    new CountryInfo("Central African Republic", "+236"),
                    new CountryInfo("Chad", "+235"),
                    new CountryInfo("Chile", "+56"),
                    new CountryInfo("China", "+86"),
                    new CountryInfo("Colombia", "+57"),
                    new CountryInfo("Comoros", "+269"),
                    new CountryInfo("Congo, Democratic Republic of the", "+243"),
                    new CountryInfo("Congo, Republic of the", "+242"),
                    new CountryInfo("Costa Rica", "+506"),
                    new CountryInfo("Croatia", "+385"),
                    new CountryInfo("Cuba", "+53"),
                    new CountryInfo("Cyprus", "+357"),
                    new CountryInfo("Czech Republic", "+420"),
                    new CountryInfo("Denmark", "+45"),
                    new CountryInfo("Djibouti", "+253"),
                    new CountryInfo("Dominica", "+1-767"),
                    new CountryInfo("Dominican Republic", "+1-809"), // and +1-829, +1-849
                    new CountryInfo("East Timor (Timor-Leste)", "+670"),
                    new CountryInfo("Ecuador", "+593"),
                    new CountryInfo("Egypt", "+20"),
                    new CountryInfo("El Salvador", "+503"),
                    new CountryInfo("Equatorial Guinea", "+240"),
                    new CountryInfo("Eritrea", "+291"),
                    new CountryInfo("Estonia", "+372"),
                    new CountryInfo("Eswatini", "+268"),
                    new CountryInfo("Ethiopia", "+251"),
                    new CountryInfo("Fiji", "+679"),
                    new CountryInfo("Finland", "+358"),
                    new CountryInfo("France", "+33"),
                    new CountryInfo("Gabon", "+241"),
                    new CountryInfo("Gambia", "+220"),
                    new CountryInfo("Georgia", "+995"),
                    new CountryInfo("Germany", "+49"),
                    new CountryInfo("Ghana", "+233"),
                    new CountryInfo("Greece", "+30"),
                    new CountryInfo("Grenada", "+1-473"),
                    new CountryInfo("Guatemala", "+502"),
                    new CountryInfo("Guinea", "+224"),
                    new CountryInfo("Guinea-Bissau", "+245"),
                    new CountryInfo("Guyana", "+592"),
                    new CountryInfo("Haiti", "+509"),
                    new CountryInfo("Honduras", "+504"),
                    new CountryInfo("Hungary", "+36"),
                    new CountryInfo("Iceland", "+354"),
                    new CountryInfo("India", "+91"),
                    new CountryInfo("Indonesia", "+62"),
                    new CountryInfo("Iran", "+98"),
                    new CountryInfo("Iraq", "+964"),
                    new CountryInfo("Ireland", "+353"),
                    new CountryInfo("Italy", "+39"),
                    new CountryInfo("Jamaica", "+1-876"),
                    new CountryInfo("Japan", "+81"),
                    new CountryInfo("Jordan", "+962"),
                    new CountryInfo("Kazakhstan", "+7"),
                    new CountryInfo("Kenya", "+254"),
                    new CountryInfo("Kiribati", "+686"),
                    new CountryInfo("Korea, North", "+850"),
                    new CountryInfo("Korea, South", "+82"),
                    new CountryInfo("Kosovo", "+383"),
                    new CountryInfo("Kuwait", "+965"),
                    new CountryInfo("Kyrgyzstan", "+996"),
                    new CountryInfo("Laos", "+856"),
                    new CountryInfo("Latvia", "+371"),
                    new CountryInfo("Lebanon", "+961"),
                    new CountryInfo("Lesotho", "+266"),
                    new CountryInfo("Liberia", "+231"),
                    new CountryInfo("Libya", "+218"),
                    new CountryInfo("Liechtenstein", "+423"),
                    new CountryInfo("Lithuania", "+370"),
                    new CountryInfo("Luxembourg", "+352"),
                    new CountryInfo("Madagascar", "+261"),
                    new CountryInfo("Malawi", "+265"),
                    new CountryInfo("Malaysia", "+60"),
                    new CountryInfo("Maldives", "+960"),
                    new CountryInfo("Mali", "+223"),
                    new CountryInfo("Malta", "+356"),
                    new CountryInfo("Marshall Islands", "+692"),
                    new CountryInfo("Mauritania", "+222"),
                    new CountryInfo("Mauritius", "+230"),
                    new CountryInfo("Mexico", "+52"),
                    new CountryInfo("Micronesia", "+691"),
                    new CountryInfo("Moldova", "+373"),
                    new CountryInfo("Monaco", "+377"),
                    new CountryInfo("Mongolia", "+976"),
                    new CountryInfo("Montenegro", "+382"),
                    new CountryInfo("Morocco", "+212"),
                    new CountryInfo("Mozambique", "+258"),
                    new CountryInfo("Myanmar", "+95"),
                    new CountryInfo("Namibia", "+264"),
                    new CountryInfo("Nauru", "+674"),
                    new CountryInfo("Nepal", "+977"),
                    new CountryInfo("Netherlands", "+31"),
                    new CountryInfo("New Zealand", "+64"),
                    new CountryInfo("Nicaragua", "+505"),
                    new CountryInfo("Niger", "+227"),
                    new CountryInfo("Nigeria", "+234"),
                    new CountryInfo("North Macedonia", "+389"),
                    new CountryInfo("Norway", "+47"),
                    new CountryInfo("Oman", "+968"),
                    new CountryInfo("Pakistan", "+92"),
                    new CountryInfo("Palau", "+680"),
                    new CountryInfo("Palestine", "+970"),
                    new CountryInfo("Panama", "+507"),
                    new CountryInfo("Papua New Guinea", "+675"),
                    new CountryInfo("Paraguay", "+595"),
                    new CountryInfo("Peru", "+51"),
                    new CountryInfo("Philippines", "+63"),
                    new CountryInfo("Poland", "+48"),
                    new CountryInfo("Portugal", "+351"),
                    new CountryInfo("Qatar", "+974"),
                    new CountryInfo("Romania", "+40"),
                    new CountryInfo("Russia", "+7"),
                    new CountryInfo("Rwanda", "+250"),
                    new CountryInfo("Saint Kitts and Nevis", "+1-869"),
                    new CountryInfo("Saint Lucia", "+1-758"),
                    new CountryInfo("Saint Vincent and the Grenadines", "+1-784"),
                    new CountryInfo("Samoa", "+685"),
                    new CountryInfo("San Marino", "+378"),
                    new CountryInfo("Sao Tome and Principe", "+239"),
                    new CountryInfo("Saudi Arabia", "+966"),
                    new CountryInfo("Senegal", "+221"),
                    new CountryInfo("Serbia", "+381"),
                    new CountryInfo("Seychelles", "+248"),
                    new CountryInfo("Sierra Leone", "+232"),
                    new CountryInfo("Singapore", "+65"),
                    new CountryInfo("Slovakia", "+421"),
                    new CountryInfo("Slovenia", "+386"),
                    new CountryInfo("Solomon Islands", "+677"),
                    new CountryInfo("Somalia", "+252"),
                    new CountryInfo("South Africa", "+27"),
                    new CountryInfo("South Sudan", "+211"),
                    new CountryInfo("Spain", "+34"),
                    new CountryInfo("Sri Lanka", "+94"),
                    new CountryInfo("Sudan", "+249"),
                    new CountryInfo("Suriname", "+597"),
                    new CountryInfo("Sweden", "+46"),
                    new CountryInfo("Switzerland", "+41"),
                    new CountryInfo("Syria", "+963"),
                    new CountryInfo("Taiwan", "+886"),
                    new CountryInfo("Tajikistan", "+992"),
                    new CountryInfo("Tanzania", "+255"),
                    new CountryInfo("Thailand", "+66"),
                    new CountryInfo("Togo", "+228"),
                    new CountryInfo("Tonga", "+676"),
                    new CountryInfo("Trinidad and Tobago", "+1-868"),
                    new CountryInfo("Tunisia", "+216"),
                    new CountryInfo("Turkey", "+90"),
                    new CountryInfo("Turkmenistan", "+993"),
                    new CountryInfo("Tuvalu", "+688"),
                    new CountryInfo("Uganda", "+256"),
                    new CountryInfo("Ukraine", "+380"),
                    new CountryInfo("United Arab Emirates", "+971"),
                    new CountryInfo("United Kingdom", "+44"),
                    new CountryInfo("United States", "+1"),
                    new CountryInfo("Uruguay", "+598"),
                    new CountryInfo("Uzbekistan", "+998"),
                    new CountryInfo("Vanuatu", "+678"),
                    new CountryInfo("Vatican City", "+39"),
                    new CountryInfo("Venezuela", "+58"),
                    new CountryInfo("Vietnam", "+84"),
                    new CountryInfo("Yemen", "+967"),
                    new CountryInfo("Zambia", "+260"),
                    new CountryInfo("Zimbabwe", "+263"),
                };
        }
    }
}
